/**
 * GitHub commit-history data layer.
 *
 * GitHub's GraphQL `contributionsCollection` exposes commit counts (`totalCommitContributions`)
 * only as a scalar per from/to window, and a window may span at most one year. To build a
 * lifetime curve we slice the account's lifetime into **monthly** windows, fetch them in
 * batched aliased queries (one query per N months — see BATCH), then accumulate into a
 * cumulative series.
 *
 * We deliberately use `totalCommitContributions` (commits-only, same definition as the green
 * contribution graph) rather than the contribution calendar, which mixes in issues/PRs/reviews.
 *
 * Alongside commits we also collect the other **public** contribution-type scalars the same
 * collection exposes — issues opened, PRs opened, PR reviews, repositories created — at the same
 * monthly resolution. These are stored but NOT plotted on the commit graph; they power per-type
 * breakdowns and change indicators (follow-up issues). `restrictedContributionsCount` remains a
 * separate, opaque all-types count that GitHub does not break down by type.
 */

const GITHUB_GRAPHQL = "https://api.github.com/graphql";

// GitHub usernames: alphanumeric or single hyphens, 1-39 chars. We validate so we can safely
// interpolate the login into the query string (dates are generated by us, never user input).
const LOGIN_RE = /^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,37}[a-zA-Z0-9])?$/;

// Months per GraphQL request. `contributionsCollection` is expensive — one alias per month for a
// whole lifetime trips GitHub's "resource limits for this query exceeded" on older accounts.
const BATCH = 12;

export interface Profile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	/** Follower count at fetch time. */
	followers: number;
	/** Following count at fetch time. */
	following: number;
	/** Public repos owned by the user. */
	publicRepos: number;
}

export interface CommitPoint {
	/** First day of the month, ISO date (YYYY-MM-DD). */
	date: string;
	/** Public commits attributed in that month. */
	commits: number;
	/** Running total of public commits up to and including that month. */
	cumulative: number;
	/**
	 * GitHub "private contributions" in that month (restrictedContributionsCount) — an opaque,
	 * all-types count GitHub only exposes when the user shows private contributions on their
	 * profile. Kept SEPARATE from `commits`; never summed into it.
	 */
	restricted: number;
	/** Running total of private contributions. */
	restrictedCumulative: number;
	/** Public issues opened in that month. */
	issues: number;
	/** Public pull requests opened in that month. */
	pullRequests: number;
	/** Public pull-request reviews in that month. */
	reviews: number;
	/** Public repositories created in that month. */
	repos: number;
}

/** Per-month counts as fetched from GitHub, before accumulation. */
export interface MonthlyCount {
	commits: number;
	restricted: number;
	issues: number;
	pullRequests: number;
	reviews: number;
	repos: number;
}

export interface CommitHistory {
	user: Profile;
	points: CommitPoint[];
	/** Lifetime public commits. */
	total: number;
	/** Lifetime private contributions (0 unless the user exposes them). */
	totalRestricted: number;
	/** Lifetime public issues opened. */
	totalIssues: number;
	/** Lifetime public pull requests opened. */
	totalPullRequests: number;
	/** Lifetime public pull-request reviews. */
	totalReviews: number;
	/** Lifetime public repositories created. */
	totalRepos: number;
}

/** Sum the additional public contribution-type counts across a series of points. */
export function sumContributionTypes(points: CommitPoint[]): {
	totalIssues: number;
	totalPullRequests: number;
	totalReviews: number;
	totalRepos: number;
} {
	return points.reduce(
		(acc, p) => ({
			totalIssues: acc.totalIssues + p.issues,
			totalPullRequests: acc.totalPullRequests + p.pullRequests,
			totalReviews: acc.totalReviews + p.reviews,
			totalRepos: acc.totalRepos + p.repos,
		}),
		{ totalIssues: 0, totalPullRequests: 0, totalReviews: 0, totalRepos: 0 },
	);
}

export class GitHubError extends Error {
	constructor(
		message: string,
		readonly status: number,
	) {
		super(message);
		this.name = "GitHubError";
	}
}

export interface MonthWindow {
	/** Inclusive start, ISO datetime. */
	from: string;
	/** Inclusive end, ISO datetime. */
	to: string;
	/** First-of-month label, YYYY-MM-DD. */
	label: string;
}

/**
 * Generate monthly windows from `start` up to and including the last *completed* month before
 * `now`. The current, in-progress month is deliberately excluded: it holds only a few days of
 * data, so plotting it flattens every curve at the end and skews totals/leaderboard. It rolls
 * back in automatically once the month completes.
 */
export function monthlyWindows(start: Date, now: Date): MonthWindow[] {
	const windows: MonthWindow[] = [];
	let year = start.getUTCFullYear();
	let month = start.getUTCMonth(); // 0-indexed
	const endYear = now.getUTCFullYear();
	const endMonth = now.getUTCMonth();

	// Strict `<` on the current month → stop before it (only completed months are included).
	while (year < endYear || (year === endYear && month < endMonth)) {
		const from = new Date(Date.UTC(year, month, 1, 0, 0, 0));
		// Last instant of this month = day 0 of next month.
		const to = new Date(Date.UTC(year, month + 1, 0, 23, 59, 59));
		const mm = String(month + 1).padStart(2, "0");
		windows.push({
			from: from.toISOString(),
			to: to.toISOString(),
			label: `${year}-${mm}-01`,
		});
		month += 1;
		if (month > 11) {
			month = 0;
			year += 1;
		}
	}
	return windows;
}

async function graphql<T>(token: string, query: string): Promise<T> {
	const res = await fetch(GITHUB_GRAPHQL, {
		method: "POST",
		headers: {
			Authorization: `Bearer ${token}`,
			"Content-Type": "application/json",
			"User-Agent": "commit-history",
		},
		body: JSON.stringify({ query }),
	});

	if (res.status === 401) {
		throw new GitHubError("GitHub token is missing or invalid.", 401);
	}
	if (!res.ok) {
		throw new GitHubError(`GitHub API error (${res.status}).`, res.status);
	}

	const json = (await res.json()) as {
		data?: T;
		errors?: Array<{ message: string }>;
	};
	if (json.errors?.length) {
		const msg = json.errors.map((e) => e.message).join("; ");
		const status = /could not resolve to a user/i.test(msg) ? 404 : 502;
		throw new GitHubError(msg, status);
	}
	if (!json.data) throw new GitHubError("Empty response from GitHub.", 502);
	return json.data;
}

function assertLogin(rawLogin: string): string {
	const login = rawLogin.trim();
	if (!LOGIN_RE.test(login)) {
		throw new GitHubError(`"${rawLogin}" is not a valid GitHub username.`, 400);
	}
	return login;
}

/** Raw shape from GraphQL, before flattening the `{ totalCount }` connections. */
interface RawProfile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	followers: { totalCount: number };
	following: { totalCount: number };
	repositories: { totalCount: number };
}

/**
 * Fetch the profile + account creation date (defines the window range) plus cheap profile
 * metadata (followers/following/public repos, bio, company, location, links). All of this comes
 * from the *same* single `user` query — no extra requests.
 */
export async function fetchProfile(
	rawLogin: string,
	token: string,
): Promise<Profile> {
	const login = assertLogin(rawLogin);
	const data = await graphql<{ user: RawProfile | null }>(
		token,
		`query { user(login: "${login}") {
			login name avatarUrl createdAt bio company location websiteUrl twitterUsername
			followers { totalCount }
			following { totalCount }
			repositories(ownerAffiliations: OWNER, privacy: PUBLIC) { totalCount }
		} }`,
	);
	if (!data.user) throw new GitHubError(`User "${login}" not found.`, 404);
	const u = data.user;
	return {
		login: u.login,
		name: u.name,
		avatarUrl: u.avatarUrl,
		createdAt: u.createdAt,
		bio: u.bio,
		company: u.company,
		location: u.location,
		websiteUrl: u.websiteUrl,
		twitterUsername: u.twitterUsername,
		followers: u.followers.totalCount,
		following: u.following.totalCount,
		publicRepos: u.repositories.totalCount,
	};
}

/**
 * Fetch per-month public commits + private contributions for the given windows, batched into
 * parallel queries. Returns counts aligned 1:1 with `windows`. The cache uses this to refresh
 * only the trailing months instead of refetching a whole lifetime.
 */
export async function fetchMonthlyCommits(
	rawLogin: string,
	token: string,
	windows: MonthWindow[],
): Promise<MonthlyCount[]> {
	const login = assertLogin(rawLogin);
	if (windows.length === 0) return [];

	const batches: MonthWindow[][] = [];
	for (let i = 0; i < windows.length; i += BATCH) {
		batches.push(windows.slice(i, i + BATCH));
	}

	const results = await Promise.all(
		batches.map((batch) => {
			const aliases = batch
				.map(
					(w, i) =>
						`w${i}: contributionsCollection(from: "${w.from}", to: "${w.to}") { totalCommitContributions restrictedContributionsCount totalIssueContributions totalPullRequestContributions totalPullRequestReviewContributions totalRepositoryContributions }`,
				)
				.join("\n");
			return graphql<{
				user: Record<
					string,
					{
						totalCommitContributions: number;
						restrictedContributionsCount: number;
						totalIssueContributions: number;
						totalPullRequestContributions: number;
						totalPullRequestReviewContributions: number;
						totalRepositoryContributions: number;
					}
				>;
			}>(token, `query { user(login: "${login}") { ${aliases} } }`);
		}),
	);

	return results.flatMap((res, b) =>
		batches[b].map((_, i) => {
			const w = res.user[`w${i}`];
			return {
				commits: w?.totalCommitContributions ?? 0,
				restricted: w?.restrictedContributionsCount ?? 0,
				issues: w?.totalIssueContributions ?? 0,
				pullRequests: w?.totalPullRequestContributions ?? 0,
				reviews: w?.totalPullRequestReviewContributions ?? 0,
				repos: w?.totalRepositoryContributions ?? 0,
			};
		}),
	);
}

/** Accumulate per-month counts into separate cumulative series (public + private). */
export function buildPoints(
	windows: MonthWindow[],
	monthly: MonthlyCount[],
): CommitPoint[] {
	let cumulative = 0;
	let restrictedCumulative = 0;
	return windows.map((w, i) => {
		const m = monthly[i];
		const commits = m?.commits ?? 0;
		const restricted = m?.restricted ?? 0;
		cumulative += commits;
		restrictedCumulative += restricted;
		return {
			date: w.label,
			commits,
			cumulative,
			restricted,
			restrictedCumulative,
			issues: m?.issues ?? 0,
			pullRequests: m?.pullRequests ?? 0,
			reviews: m?.reviews ?? 0,
			repos: m?.repos ?? 0,
		};
	});
}

/** Fetch a user's full lifetime commit history (no cache). */
export async function fetchCommitHistory(
	rawLogin: string,
	token: string,
): Promise<CommitHistory> {
	if (!token)
		throw new GitHubError("No GitHub token configured on the server.", 401);
	const user = await fetchProfile(rawLogin, token);
	const windows = monthlyWindows(new Date(user.createdAt), new Date());
	const monthly = await fetchMonthlyCommits(user.login, token, windows);
	const points = buildPoints(windows, monthly);
	const last = points.at(-1);
	return {
		user,
		points,
		total: last?.cumulative ?? 0,
		totalRestricted: last?.restrictedCumulative ?? 0,
		...sumContributionTypes(points),
	};
}
