/**
 * GitHub commit-history data layer.
 *
 * GitHub's GraphQL `contributionsCollection` exposes commit counts (`totalCommitContributions`)
 * only as a scalar per from/to window, and a window may span at most one year. To build a
 * lifetime curve we slice the account's lifetime into **monthly** windows, fetch them in
 * batched aliased queries (one query per N months — see BATCH), then accumulate into a
 * cumulative series.
 *
 * We deliberately use `totalCommitContributions` (commits-only, same definition as the green
 * contribution graph) rather than the contribution calendar, which mixes in issues/PRs/reviews.
 *
 * Alongside commits we also collect the other **public** contribution-type scalars the same
 * collection exposes — issues opened, PRs opened, PR reviews, repositories created — at the same
 * monthly resolution. These are stored but NOT plotted on the commit graph; they power per-type
 * breakdowns and change indicators (follow-up issues). `restrictedContributionsCount` remains a
 * separate, opaque all-types count that GitHub does not break down by type.
 */

const GITHUB_GRAPHQL = "https://api.github.com/graphql";

// GitHub usernames: alphanumeric or single hyphens, 1-39 chars. We validate so we can safely
// interpolate the login into the query string (dates are generated by us, never user input).
const LOGIN_RE = /^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,37}[a-zA-Z0-9])?$/;

// Months per GraphQL request. `contributionsCollection` is expensive, and there are two opposing
// limits: too MANY aliases in one query trips GitHub's "resource limits for this query exceeded",
// while too many EXPENSIVE aliases makes GitHub's gateway time the query out (504) — e.g. a
// 12-month batch for a hyper-active account like `taylorotwell` reliably 504s at ~11s, whereas a
// 6-month batch returns in ~5s. 6 keeps us comfortably under both ceilings.
const BATCH = 6;

// `contributionsCollection` queries are slow, and firing a whole lifetime at once (old accounts
// span a dozen-plus batches) makes GitHub time them out (502) AND trips its secondary-rate-limit /
// abuse detector (403 with a multi-minute Retry-After) — which poisons the shared token for every
// other visitor. So we cap the number of batches in flight and retry transient failures with
// backoff instead of bursting. See MAX_BACKOFF_MS for why we don't fully honor long Retry-Afters.
const CONCURRENCY = 3;
const MAX_ATTEMPTS = 3;
// Longest we'll block a single request while backing off. A long Retry-After (GitHub hands out
// 60-300s once its abuse detector trips) is useless inside a serverless request that has ~seconds
// to live, so we cap the wait and fail fast to a stale/error response rather than hang.
const MAX_BACKOFF_MS = 4000;
// Statuses worth retrying: secondary-rate-limit (403), rate limit (429), and transient 5xx
// (502 also covers GraphQL-level errors we map below, e.g. heavy-query timeouts).
const RETRYABLE_STATUS = new Set([403, 429, 500, 502, 503, 504]);

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Run `fn` over `items` with at most `limit` concurrent calls, preserving input order in the
 * result. Replaces a `Promise.all` fan-out so we never burst GitHub with a lifetime of batches.
 */
async function mapWithConcurrency<T, R>(
	items: T[],
	limit: number,
	fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
	const results = new Array<R>(items.length);
	let next = 0;
	async function worker() {
		while (next < items.length) {
			const i = next++;
			results[i] = await fn(items[i], i);
		}
	}
	await Promise.all(
		Array.from({ length: Math.min(limit, items.length) }, worker),
	);
	return results;
}

export interface Profile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	/** Follower count at fetch time. */
	followers: number;
	/** Following count at fetch time. */
	following: number;
	/** Public repos owned by the user. */
	publicRepos: number;
}

export interface CommitPoint {
	/** First day of the month, ISO date (YYYY-MM-DD). */
	date: string;
	/** Public commits attributed in that month. */
	commits: number;
	/** Running total of public commits up to and including that month. */
	cumulative: number;
	/**
	 * GitHub "private contributions" in that month (restrictedContributionsCount) — an opaque,
	 * all-types count GitHub only exposes when the user shows private contributions on their
	 * profile. Kept SEPARATE from `commits`; never summed into it.
	 */
	restricted: number;
	/** Running total of private contributions. */
	restrictedCumulative: number;
	/** Public issues opened in that month. */
	issues: number;
	/** Public pull requests opened in that month. */
	pullRequests: number;
	/** Public pull-request reviews in that month. */
	reviews: number;
	/** Public repositories created in that month. */
	repos: number;
}

/** Per-month counts as fetched from GitHub, before accumulation. */
export interface MonthlyCount {
	commits: number;
	restricted: number;
	issues: number;
	pullRequests: number;
	reviews: number;
	repos: number;
}

export interface CommitHistory {
	user: Profile;
	points: CommitPoint[];
	/** Lifetime public commits. */
	total: number;
	/** Lifetime private contributions (0 unless the user exposes them). */
	totalRestricted: number;
	/** Lifetime public issues opened. */
	totalIssues: number;
	/** Lifetime public pull requests opened. */
	totalPullRequests: number;
	/** Lifetime public pull-request reviews. */
	totalReviews: number;
	/** Lifetime public repositories created. */
	totalRepos: number;
}

/** Sum the additional public contribution-type counts across a series of points. */
export function sumContributionTypes(points: CommitPoint[]): {
	totalIssues: number;
	totalPullRequests: number;
	totalReviews: number;
	totalRepos: number;
} {
	return points.reduce(
		(acc, p) => ({
			totalIssues: acc.totalIssues + p.issues,
			totalPullRequests: acc.totalPullRequests + p.pullRequests,
			totalReviews: acc.totalReviews + p.reviews,
			totalRepos: acc.totalRepos + p.repos,
		}),
		{ totalIssues: 0, totalPullRequests: 0, totalReviews: 0, totalRepos: 0 },
	);
}

export class GitHubError extends Error {
	constructor(
		message: string,
		readonly status: number,
	) {
		super(message);
		this.name = "GitHubError";
	}
}

export interface MonthWindow {
	/** Inclusive start, ISO datetime. */
	from: string;
	/** Inclusive end, ISO datetime. */
	to: string;
	/** First-of-month label, YYYY-MM-DD. */
	label: string;
}

/**
 * Generate monthly windows from `start` up to and including the last *completed* month before
 * `now`. The current, in-progress month is deliberately excluded: it holds only a few days of
 * data, so plotting it flattens every curve at the end and skews totals/leaderboard. It rolls
 * back in automatically once the month completes.
 */
export function monthlyWindows(start: Date, now: Date): MonthWindow[] {
	const windows: MonthWindow[] = [];
	let year = start.getUTCFullYear();
	let month = start.getUTCMonth(); // 0-indexed
	const endYear = now.getUTCFullYear();
	const endMonth = now.getUTCMonth();

	// Strict `<` on the current month → stop before it (only completed months are included).
	while (year < endYear || (year === endYear && month < endMonth)) {
		const from = new Date(Date.UTC(year, month, 1, 0, 0, 0));
		// Last instant of this month = day 0 of next month.
		const to = new Date(Date.UTC(year, month + 1, 0, 23, 59, 59));
		const mm = String(month + 1).padStart(2, "0");
		windows.push({
			from: from.toISOString(),
			to: to.toISOString(),
			label: `${year}-${mm}-01`,
		});
		month += 1;
		if (month > 11) {
			month = 0;
			year += 1;
		}
	}
	return windows;
}

/** One GitHub GraphQL request, no retries. `retryAfterMs` carries a parsed Retry-After (if any). */
async function graphqlOnce<T>(
	token: string,
	query: string,
): Promise<{ data: T } | { error: GitHubError; retryAfterMs: number | null }> {
	const res = await fetch(GITHUB_GRAPHQL, {
		method: "POST",
		headers: {
			Authorization: `Bearer ${token}`,
			"Content-Type": "application/json",
			"User-Agent": "commit-history",
		},
		body: JSON.stringify({ query }),
	});

	if (res.status === 401) {
		throw new GitHubError("GitHub token is missing or invalid.", 401);
	}
	if (!res.ok) {
		const ra = Number(res.headers.get("retry-after"));
		return {
			error: new GitHubError(`GitHub API error (${res.status}).`, res.status),
			retryAfterMs: Number.isFinite(ra) && ra > 0 ? ra * 1000 : null,
		};
	}

	const json = (await res.json()) as {
		data?: T;
		errors?: Array<{ message: string }>;
	};
	if (json.errors?.length) {
		const msg = json.errors.map((e) => e.message).join("; ");
		// A missing user is a hard 404; anything else (incl. heavy-query timeouts) is a transient 502.
		if (/could not resolve to a user/i.test(msg)) {
			throw new GitHubError(msg, 404);
		}
		return { error: new GitHubError(msg, 502), retryAfterMs: null };
	}
	if (!json.data) {
		return {
			error: new GitHubError("Empty response from GitHub.", 502),
			retryAfterMs: null,
		};
	}
	return { data: json.data };
}

/**
 * GitHub GraphQL request with bounded retries. Transient failures (secondary-rate-limit, 429,
 * 5xx, heavy-query timeouts) are retried with capped backoff; hard failures (401/404) throw
 * immediately. Backoff honors Retry-After but is clamped to MAX_BACKOFF_MS so a request never
 * hangs on GitHub's multi-minute abuse cooldowns.
 */
async function graphql<T>(token: string, query: string): Promise<T> {
	let lastError: GitHubError | undefined;
	for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
		const result = await graphqlOnce<T>(token, query);
		if ("data" in result) return result.data;

		lastError = result.error;
		if (
			!RETRYABLE_STATUS.has(result.error.status) ||
			attempt === MAX_ATTEMPTS
		) {
			throw result.error;
		}
		const backoff =
			result.retryAfterMs != null
				? Math.min(result.retryAfterMs, MAX_BACKOFF_MS)
				: Math.min(500 * 2 ** (attempt - 1), MAX_BACKOFF_MS);
		await sleep(backoff);
	}
	// Unreachable (the loop either returns or throws), but keeps the type checker happy.
	throw lastError ?? new GitHubError("GitHub request failed.", 502);
}

function assertLogin(rawLogin: string): string {
	const login = rawLogin.trim();
	if (!LOGIN_RE.test(login)) {
		throw new GitHubError(`"${rawLogin}" is not a valid GitHub username.`, 400);
	}
	return login;
}

/** Raw shape from GraphQL, before flattening the `{ totalCount }` connections. */
interface RawProfile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	followers: { totalCount: number };
	following: { totalCount: number };
	repositories: { totalCount: number };
}

/**
 * Fetch the profile + account creation date (defines the window range) plus cheap profile
 * metadata (followers/following/public repos, bio, company, location, links). All of this comes
 * from the *same* single `user` query — no extra requests.
 */
export async function fetchProfile(
	rawLogin: string,
	token: string,
): Promise<Profile> {
	const login = assertLogin(rawLogin);
	const data = await graphql<{ user: RawProfile | null }>(
		token,
		`query { user(login: "${login}") {
			login name avatarUrl createdAt bio company location websiteUrl twitterUsername
			followers { totalCount }
			following { totalCount }
			repositories(ownerAffiliations: OWNER, privacy: PUBLIC) { totalCount }
		} }`,
	);
	if (!data.user) throw new GitHubError(`User "${login}" not found.`, 404);
	const u = data.user;
	return {
		login: u.login,
		name: u.name,
		avatarUrl: u.avatarUrl,
		createdAt: u.createdAt,
		bio: u.bio,
		company: u.company,
		location: u.location,
		websiteUrl: u.websiteUrl,
		twitterUsername: u.twitterUsername,
		followers: u.followers.totalCount,
		following: u.following.totalCount,
		publicRepos: u.repositories.totalCount,
	};
}

/**
 * Fetch per-month public commits + private contributions for the given windows, batched and run
 * with bounded concurrency (see CONCURRENCY). Returns counts aligned 1:1 with `windows`. The cache
 * uses this to refresh only the trailing months instead of refetching a whole lifetime.
 */
export async function fetchMonthlyCommits(
	rawLogin: string,
	token: string,
	windows: MonthWindow[],
): Promise<MonthlyCount[]> {
	const login = assertLogin(rawLogin);
	if (windows.length === 0) return [];

	const batches: MonthWindow[][] = [];
	for (let i = 0; i < windows.length; i += BATCH) {
		batches.push(windows.slice(i, i + BATCH));
	}

	const results = await mapWithConcurrency(batches, CONCURRENCY, (batch) => {
		const aliases = batch
			.map(
				(w, i) =>
					`w${i}: contributionsCollection(from: "${w.from}", to: "${w.to}") { totalCommitContributions restrictedContributionsCount totalIssueContributions totalPullRequestContributions totalPullRequestReviewContributions totalRepositoryContributions }`,
			)
			.join("\n");
		return graphql<{
			user: Record<
				string,
				{
					totalCommitContributions: number;
					restrictedContributionsCount: number;
					totalIssueContributions: number;
					totalPullRequestContributions: number;
					totalPullRequestReviewContributions: number;
					totalRepositoryContributions: number;
				}
			>;
		}>(token, `query { user(login: "${login}") { ${aliases} } }`);
	});

	return results.flatMap((res, b) =>
		batches[b].map((_, i) => {
			const w = res.user[`w${i}`];
			return {
				commits: w?.totalCommitContributions ?? 0,
				restricted: w?.restrictedContributionsCount ?? 0,
				issues: w?.totalIssueContributions ?? 0,
				pullRequests: w?.totalPullRequestContributions ?? 0,
				reviews: w?.totalPullRequestReviewContributions ?? 0,
				repos: w?.totalRepositoryContributions ?? 0,
			};
		}),
	);
}

/** Accumulate per-month counts into separate cumulative series (public + private). */
export function buildPoints(
	windows: MonthWindow[],
	monthly: MonthlyCount[],
): CommitPoint[] {
	let cumulative = 0;
	let restrictedCumulative = 0;
	return windows.map((w, i) => {
		const m = monthly[i];
		const commits = m?.commits ?? 0;
		const restricted = m?.restricted ?? 0;
		cumulative += commits;
		restrictedCumulative += restricted;
		return {
			date: w.label,
			commits,
			cumulative,
			restricted,
			restrictedCumulative,
			issues: m?.issues ?? 0,
			pullRequests: m?.pullRequests ?? 0,
			reviews: m?.reviews ?? 0,
			repos: m?.repos ?? 0,
		};
	});
}

/** Fetch a user's full lifetime commit history (no cache). */
export async function fetchCommitHistory(
	rawLogin: string,
	token: string,
): Promise<CommitHistory> {
	if (!token)
		throw new GitHubError("No GitHub token configured on the server.", 401);
	const user = await fetchProfile(rawLogin, token);
	const windows = monthlyWindows(new Date(user.createdAt), new Date());
	const monthly = await fetchMonthlyCommits(user.login, token, windows);
	const points = buildPoints(windows, monthly);
	const last = points.at(-1);
	return {
		user,
		points,
		total: last?.cumulative ?? 0,
		totalRestricted: last?.restrictedCumulative ?? 0,
		...sumContributionTypes(points),
	};
}
