/**
 * GitHub commit-history data layer.
 *
 * GitHub's GraphQL `contributionsCollection` exposes commit counts (`totalCommitContributions`)
 * only as a scalar per from/to window, and a window may span at most one year. To build a
 * lifetime curve we slice the account's lifetime into **monthly** windows, fetch them in
 * batched aliased queries (one query per N months — see BATCH), then accumulate into a
 * cumulative series.
 *
 * We deliberately use `totalCommitContributions` (commits-only, same definition as the green
 * contribution graph) rather than the contribution calendar, which mixes in issues/PRs/reviews.
 *
 * Alongside commits we also collect the other **public** contribution-type scalars the same
 * collection exposes — issues opened, PRs opened, PR reviews, repositories created — at the same
 * monthly resolution. These are stored but NOT plotted on the commit graph; they power per-type
 * breakdowns and change indicators (follow-up issues). `restrictedContributionsCount` remains a
 * separate, opaque all-types count that GitHub does not break down by type.
 */

const GITHUB_GRAPHQL = "https://api.github.com/graphql";

// GitHub usernames: alphanumeric or single hyphens, 1-39 chars. We validate so we can safely
// interpolate the login into the query string (dates are generated by us, never user input).
const LOGIN_RE = /^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,37}[a-zA-Z0-9])?$/;

// Months per GraphQL request. `contributionsCollection` is expensive, and there are two opposing
// limits: too MANY aliases in one query trips GitHub's "resource limits for this query exceeded",
// while too many EXPENSIVE aliases makes GitHub's gateway time the query out (504) — e.g. a
// 12-month batch for a hyper-active account like `taylorotwell` reliably 504s at ~11s, whereas a
// 6-month batch returns in ~5s. 6 keeps us comfortably under both ceilings.
const BATCH = 6;

// `contributionsCollection` queries are slow, and firing a whole lifetime at once (old accounts
// span a dozen-plus batches) makes GitHub time them out (502) AND trips its secondary-rate-limit /
// abuse detector (403 with a multi-minute Retry-After) — which poisons the shared token for every
// other visitor. So we cap the number of batches in flight, retry transient 5xx with backoff, and
// fail fast on rate limits instead of bursting (see RETRYABLE_STATUS).
const CONCURRENCY = 3;
const MAX_ATTEMPTS = 3;
// Longest we'll block a single request while backing off between 5xx retries — a serverless
// request only has ~seconds to live, so we never wait longer than this.
const MAX_BACKOFF_MS = 4000;
// Statuses worth retrying: transient 5xx only (502 also covers GraphQL-level errors we map below,
// e.g. heavy-query timeouts). Rate limits (403 secondary/abuse, 429) are deliberately NOT retried:
// GitHub hands out 60-300s Retry-Afters and documents that retrying before they elapse extends
// the cooldown — inside a request that lives seconds, an early retry can only prolong the ban on
// the shared token for every visitor. Fail fast and let the cache serve what it has.
const RETRYABLE_STATUS = new Set([500, 502, 503, 504]);

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Run `fn` over `items` with at most `limit` concurrent calls, preserving input order in the
 * result. Replaces a `Promise.all` fan-out so we never burst GitHub with a lifetime of batches.
 */
async function mapWithConcurrency<T, R>(
	items: T[],
	limit: number,
	fn: (item: T, index: number) => Promise<R>,
): Promise<R[]> {
	const results = new Array<R>(items.length);
	let next = 0;
	async function worker() {
		while (next < items.length) {
			const i = next++;
			results[i] = await fn(items[i], i);
		}
	}
	await Promise.all(
		Array.from({ length: Math.min(limit, items.length) }, worker),
	);
	return results;
}

export interface Profile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	/** Follower count at fetch time. */
	followers: number;
	/** Following count at fetch time. */
	following: number;
	/** Public repos owned by the user. */
	publicRepos: number;
}

export interface CommitPoint {
	/** First day of the month, ISO date (YYYY-MM-DD). */
	date: string;
	/** Public commits attributed in that month. */
	commits: number;
	/** Running total of public commits up to and including that month. */
	cumulative: number;
	/**
	 * GitHub "private contributions" in that month (restrictedContributionsCount) — an opaque,
	 * all-types count GitHub only exposes when the user shows private contributions on their
	 * profile. Kept SEPARATE from `commits`; never summed into it.
	 */
	restricted: number;
	/** Running total of private contributions. */
	restrictedCumulative: number;
	/** Public issues opened in that month. */
	issues: number;
	/** Public pull requests opened in that month. */
	pullRequests: number;
	/** Public pull-request reviews in that month. */
	reviews: number;
	/** Public repositories created in that month. */
	repos: number;
}

/** Per-month counts as fetched from GitHub, before accumulation. */
export interface MonthlyCount {
	commits: number;
	restricted: number;
	issues: number;
	pullRequests: number;
	reviews: number;
	repos: number;
}

export interface CommitHistory {
	user: Profile;
	points: CommitPoint[];
	/** Lifetime public commits. */
	total: number;
	/** Lifetime private contributions (0 unless the user exposes them). */
	totalRestricted: number;
	/** Lifetime public issues opened. */
	totalIssues: number;
	/** Lifetime public pull requests opened. */
	totalPullRequests: number;
	/** Lifetime public pull-request reviews. */
	totalReviews: number;
	/** Lifetime public repositories created. */
	totalRepos: number;
}

/** Sum the additional public contribution-type counts across a series of points. */
export function sumContributionTypes(points: CommitPoint[]): {
	totalIssues: number;
	totalPullRequests: number;
	totalReviews: number;
	totalRepos: number;
} {
	return points.reduce(
		(acc, p) => ({
			totalIssues: acc.totalIssues + p.issues,
			totalPullRequests: acc.totalPullRequests + p.pullRequests,
			totalReviews: acc.totalReviews + p.reviews,
			totalRepos: acc.totalRepos + p.repos,
		}),
		{ totalIssues: 0, totalPullRequests: 0, totalReviews: 0, totalRepos: 0 },
	);
}

/** How far along an incremental history build is (see cache.ts). */
export interface BuildProgress {
	/** Months already fetched & persisted (including the stored head). */
	monthsFetched: number;
	/** Total months in the account's lifetime window. */
	monthsTotal: number;
}

export class GitHubError extends Error {
	constructor(
		message: string,
		readonly status: number,
		/** Set only on the 503 "still building" error, so callers can report progress. */
		readonly progress?: BuildProgress,
	) {
		super(message);
		this.name = "GitHubError";
	}
}

export interface MonthWindow {
	/** Inclusive start, ISO datetime. */
	from: string;
	/** Inclusive end, ISO datetime. */
	to: string;
	/** First-of-month label, YYYY-MM-DD. */
	label: string;
}

/**
 * Generate monthly windows from `start` up to and including the last *completed* month before
 * `now`. The current, in-progress month is deliberately excluded: it holds only a few days of
 * data, so plotting it flattens every curve at the end and skews totals/leaderboard. It rolls
 * back in automatically once the month completes.
 */
export function monthlyWindows(start: Date, now: Date): MonthWindow[] {
	const windows: MonthWindow[] = [];
	let year = start.getUTCFullYear();
	let month = start.getUTCMonth(); // 0-indexed
	const endYear = now.getUTCFullYear();
	const endMonth = now.getUTCMonth();

	// Strict `<` on the current month → stop before it (only completed months are included).
	while (year < endYear || (year === endYear && month < endMonth)) {
		const from = new Date(Date.UTC(year, month, 1, 0, 0, 0));
		// Last instant of this month = day 0 of next month.
		const to = new Date(Date.UTC(year, month + 1, 0, 23, 59, 59));
		const mm = String(month + 1).padStart(2, "0");
		windows.push({
			from: from.toISOString(),
			to: to.toISOString(),
			label: `${year}-${mm}-01`,
		});
		month += 1;
		if (month > 11) {
			month = 0;
			year += 1;
		}
	}
	return windows;
}

// Milliseconds in a flat 365-day span. Used instead of calendar-year arithmetic so a window can
// never exceed GraphQL's "from/to at most one year apart" cap (a Feb-29 + 1 calendar year span
// would be 366 days).
const YEAR_MS = 365 * 24 * 60 * 60 * 1000;

/**
 * Generate consecutive ≤1-year windows from `start` up to the first instant of the current
 * month — the same "exclude the in-progress month" convention as `monthlyWindows`, so totals
 * built from these stay stable within a month. Used for org-scoped *lifetime* sums, where
 * per-month resolution isn't needed and yearly windows cost ~1/12th the aliases.
 */
export function yearlyWindows(start: Date, now: Date): MonthWindow[] {
	const end = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1);
	const windows: MonthWindow[] = [];
	for (let from = start.getTime(); from < end; from += YEAR_MS) {
		// Windows abut at 1-second gaps, mirroring monthlyWindows' 23:59:59 month ends.
		const to = Math.min(from + YEAR_MS - 1000, end - 1000);
		windows.push({
			from: new Date(from).toISOString(),
			to: new Date(to).toISOString(),
			label: new Date(from).toISOString().slice(0, 10),
		});
	}
	return windows;
}

/** One GitHub GraphQL request, no retries. `retryAfterMs` carries a parsed Retry-After (if any). */
async function graphqlOnce<T>(
	token: string,
	query: string,
): Promise<{ data: T } | { error: GitHubError; retryAfterMs: number | null }> {
	const res = await fetch(GITHUB_GRAPHQL, {
		method: "POST",
		headers: {
			Authorization: `Bearer ${token}`,
			"Content-Type": "application/json",
			"User-Agent": "commit-history",
		},
		body: JSON.stringify({ query }),
	});

	if (res.status === 401) {
		throw new GitHubError("GitHub token is missing or invalid.", 401);
	}
	if (!res.ok) {
		const ra = Number(res.headers.get("retry-after"));
		return {
			error: new GitHubError(`GitHub API error (${res.status}).`, res.status),
			retryAfterMs: Number.isFinite(ra) && ra > 0 ? ra * 1000 : null,
		};
	}

	const json = (await res.json()) as {
		data?: T;
		errors?: Array<{ message: string; type?: string }>;
	};
	if (json.errors?.length) {
		const msg = json.errors.map((e) => e.message).join("; ");
		// A missing user/org is a hard 404; anything else (incl. heavy-query timeouts) is a transient 502.
		if (/could not resolve to an? (user|organization)/i.test(msg)) {
			throw new GitHubError(msg, 404);
		}
		// The primary GraphQL rate limit arrives as HTTP 200 + RATE_LIMITED — map it to 429 so it
		// fails fast like the HTTP-level rate limits instead of being retried as a transient 502.
		if (json.errors.some((e) => e.type === "RATE_LIMITED")) {
			return { error: new GitHubError(msg, 429), retryAfterMs: null };
		}
		return { error: new GitHubError(msg, 502), retryAfterMs: null };
	}
	if (!json.data) {
		return {
			error: new GitHubError("Empty response from GitHub.", 502),
			retryAfterMs: null,
		};
	}
	return { data: json.data };
}

/**
 * GitHub GraphQL request with bounded retries. Transient failures (secondary-rate-limit, 429,
 * 5xx, heavy-query timeouts) are retried with capped backoff; hard failures (401/404) throw
 * immediately. Backoff honors Retry-After but is clamped to MAX_BACKOFF_MS so a request never
 * hangs on GitHub's multi-minute abuse cooldowns.
 */
async function graphql<T>(token: string, query: string): Promise<T> {
	let lastError: GitHubError | undefined;
	for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
		const result = await graphqlOnce<T>(token, query);
		if ("data" in result) return result.data;

		lastError = result.error;
		if (
			!RETRYABLE_STATUS.has(result.error.status) ||
			attempt === MAX_ATTEMPTS
		) {
			throw result.error;
		}
		const backoff =
			result.retryAfterMs != null
				? Math.min(result.retryAfterMs, MAX_BACKOFF_MS)
				: Math.min(500 * 2 ** (attempt - 1), MAX_BACKOFF_MS);
		await sleep(backoff);
	}
	// Unreachable (the loop either returns or throws), but keeps the type checker happy.
	throw lastError ?? new GitHubError("GitHub request failed.", 502);
}

function assertLogin(rawLogin: string): string {
	const login = rawLogin.trim();
	if (!LOGIN_RE.test(login)) {
		throw new GitHubError(`"${rawLogin}" is not a valid GitHub username.`, 400);
	}
	return login;
}

/** Raw shape from GraphQL, before flattening the `{ totalCount }` connections. */
interface RawProfile {
	login: string;
	name: string | null;
	avatarUrl: string;
	createdAt: string;
	bio: string | null;
	company: string | null;
	location: string | null;
	websiteUrl: string | null;
	twitterUsername: string | null;
	followers: { totalCount: number };
	following: { totalCount: number };
	repositories: { totalCount: number };
}

/**
 * Fetch the profile + account creation date (defines the window range) plus cheap profile
 * metadata (followers/following/public repos, bio, company, location, links). All of this comes
 * from the *same* single `user` query — no extra requests.
 */
export async function fetchProfile(
	rawLogin: string,
	token: string,
): Promise<Profile> {
	const login = assertLogin(rawLogin);
	const data = await graphql<{ user: RawProfile | null }>(
		token,
		`query { user(login: "${login}") {
			login name avatarUrl createdAt bio company location websiteUrl twitterUsername
			followers { totalCount }
			following { totalCount }
			repositories(ownerAffiliations: OWNER, privacy: PUBLIC) { totalCount }
		} }`,
	);
	if (!data.user) throw new GitHubError(`User "${login}" not found.`, 404);
	const u = data.user;
	return {
		login: u.login,
		name: u.name,
		avatarUrl: u.avatarUrl,
		createdAt: u.createdAt,
		bio: u.bio,
		company: u.company,
		location: u.location,
		websiteUrl: u.websiteUrl,
		twitterUsername: u.twitterUsername,
		followers: u.followers.totalCount,
		following: u.following.totalCount,
		publicRepos: u.repositories.totalCount,
	};
}

// ── Organizations ────────────────────────────────────────────────────────────

export interface OrgProfile {
	/** GraphQL node id — keys `contributionsCollection(organizationID: …)` queries. */
	nodeId: string;
	login: string;
	name: string | null;
	avatarUrl: string;
	htmlUrl: string;
	createdAt: string;
	description: string | null;
	websiteUrl: string | null;
	location: string | null;
	twitterUsername: string | null;
	/** Domain-verified organization badge. */
	isVerified: boolean;
	/** Members visible to the token (public members only for a non-member token). */
	memberCount: number;
	/** Public repos owned by the org. */
	publicRepos: number;
}

export interface OrgMember {
	login: string;
	name: string | null;
	avatarUrl: string;
	/** Account creation — bounds the member's contribution windows with no extra request. */
	createdAt: string;
	/** 'MEMBER' | 'ADMIN' (membersWithRole edge role). */
	role: string | null;
}

interface RawOrgProfile {
	id: string;
	login: string;
	name: string | null;
	avatarUrl: string;
	url: string;
	createdAt: string;
	description: string | null;
	websiteUrl: string | null;
	location: string | null;
	twitterUsername: string | null;
	isVerified: boolean;
	membersWithRole: { totalCount: number };
	repositories: { totalCount: number };
}

/** Fetch an org's profile + node id (window anchor + org-scoped query key) in one request. */
export async function fetchOrgProfile(
	rawLogin: string,
	token: string,
): Promise<OrgProfile> {
	// Org logins obey the same rules as usernames.
	const login = assertLogin(rawLogin);
	const data = await graphql<{ organization: RawOrgProfile | null }>(
		token,
		`query { organization(login: "${login}") {
			id login name avatarUrl url createdAt description websiteUrl location twitterUsername isVerified
			membersWithRole { totalCount }
			repositories(privacy: PUBLIC) { totalCount }
		} }`,
	);
	if (!data.organization)
		throw new GitHubError(`Organization "${login}" not found.`, 404);
	const o = data.organization;
	return {
		nodeId: o.id,
		login: o.login,
		name: o.name,
		avatarUrl: o.avatarUrl,
		htmlUrl: o.url,
		createdAt: o.createdAt,
		description: o.description,
		websiteUrl: o.websiteUrl,
		location: o.location,
		twitterUsername: o.twitterUsername,
		isVerified: o.isVerified,
		memberCount: o.membersWithRole.totalCount,
		publicRepos: o.repositories.totalCount,
	};
}

// Hard stop for the members pagination loop (pages of 100). The org build enforces its own,
// lower member cap before fetching contributions — this is just a runaway/mega-org backstop.
const MAX_MEMBER_PAGES = 10;

/**
 * Enumerate an org's members visible to the token — public members only unless the token itself
 * belongs to the org. Each node carries `createdAt`, so the caller can window every member's
 * contribution fetch without per-member profile requests.
 */
export async function fetchOrgMembers(
	rawLogin: string,
	token: string,
): Promise<OrgMember[]> {
	const login = assertLogin(rawLogin);
	const members: OrgMember[] = [];
	let cursor: string | null = null;
	for (let page = 0; page < MAX_MEMBER_PAGES; page++) {
		const after: string = cursor ? `, after: "${cursor}"` : "";
		const data = await graphql<{
			organization: {
				membersWithRole: {
					pageInfo: { hasNextPage: boolean; endCursor: string | null };
					edges: Array<{
						role: string | null;
						node: {
							login: string;
							name: string | null;
							avatarUrl: string;
							createdAt: string;
						} | null;
					}>;
				};
			} | null;
		}>(
			token,
			`query { organization(login: "${login}") {
				membersWithRole(first: 100${after}) {
					pageInfo { hasNextPage endCursor }
					edges { role node { login name avatarUrl createdAt } }
				}
			} }`,
		);
		const conn = data.organization?.membersWithRole;
		if (!conn) throw new GitHubError(`Organization "${login}" not found.`, 404);
		for (const edge of conn.edges) {
			if (!edge.node) continue;
			members.push({ ...edge.node, role: edge.role });
		}
		if (!conn.pageInfo.hasNextPage) return members;
		cursor = conn.pageInfo.endCursor;
	}
	return members;
}

/** A member's summed lifetime contributions to one org (org-scoped, not their global totals). */
export interface OrgMemberTotals {
	commits: number;
	issues: number;
	pullRequests: number;
	reviews: number;
}

// GraphQL node ids come from GitHub itself (via our DB), but they get interpolated into query
// strings — validate the alphabet anyway so a corrupted row can't inject query syntax.
const NODE_ID_RE = /^[A-Za-z0-9_=+/-]+$/;

/**
 * Fetch one member's lifetime contributions *to one org*: aliased org-scoped
 * `contributionsCollection(organizationID: …)` windows, batched like `fetchMonthlyCommits`,
 * summed into a single totals tuple (per-window resolution is the later worker's job).
 * Batches run sequentially — the org build already processes members concurrently, and
 * nesting concurrency would burst past the global CONCURRENCY cap.
 */
export async function fetchOrgMemberContributions(
	rawLogin: string,
	orgNodeId: string,
	token: string,
	windows: MonthWindow[],
): Promise<OrgMemberTotals> {
	const login = assertLogin(rawLogin);
	if (!NODE_ID_RE.test(orgNodeId)) {
		throw new GitHubError(`Invalid organization node id.`, 400);
	}
	const totals: OrgMemberTotals = {
		commits: 0,
		issues: 0,
		pullRequests: 0,
		reviews: 0,
	};
	for (let i = 0; i < windows.length; i += BATCH) {
		const batch = windows.slice(i, i + BATCH);
		const aliases = batch
			.map(
				(w, j) =>
					`w${j}: contributionsCollection(organizationID: "${orgNodeId}", from: "${w.from}", to: "${w.to}") { totalCommitContributions totalIssueContributions totalPullRequestContributions totalPullRequestReviewContributions }`,
			)
			.join("\n");
		const data = await graphql<{
			user: Record<
				string,
				{
					totalCommitContributions: number;
					totalIssueContributions: number;
					totalPullRequestContributions: number;
					totalPullRequestReviewContributions: number;
				}
			> | null;
		}>(token, `query { user(login: "${login}") { ${aliases} } }`);
		if (!data.user) throw new GitHubError(`User "${login}" not found.`, 404);
		for (let j = 0; j < batch.length; j++) {
			const w = data.user[`w${j}`];
			totals.commits += w?.totalCommitContributions ?? 0;
			totals.issues += w?.totalIssueContributions ?? 0;
			totals.pullRequests += w?.totalPullRequestContributions ?? 0;
			totals.reviews += w?.totalPullRequestReviewContributions ?? 0;
		}
	}
	return totals;
}

/**
 * Fetch per-month public commits + private contributions for the given windows, batched and run
 * with bounded concurrency (see CONCURRENCY). Returns counts aligned 1:1 with `windows`. The cache
 * uses this to refresh only the trailing months instead of refetching a whole lifetime.
 */
export async function fetchMonthlyCommits(
	rawLogin: string,
	token: string,
	windows: MonthWindow[],
): Promise<MonthlyCount[]> {
	const login = assertLogin(rawLogin);
	if (windows.length === 0) return [];

	const batches: MonthWindow[][] = [];
	for (let i = 0; i < windows.length; i += BATCH) {
		batches.push(windows.slice(i, i + BATCH));
	}

	const results = await mapWithConcurrency(batches, CONCURRENCY, (batch) => {
		const aliases = batch
			.map(
				(w, i) =>
					`w${i}: contributionsCollection(from: "${w.from}", to: "${w.to}") { totalCommitContributions restrictedContributionsCount totalIssueContributions totalPullRequestContributions totalPullRequestReviewContributions totalRepositoryContributions }`,
			)
			.join("\n");
		return graphql<{
			user: Record<
				string,
				{
					totalCommitContributions: number;
					restrictedContributionsCount: number;
					totalIssueContributions: number;
					totalPullRequestContributions: number;
					totalPullRequestReviewContributions: number;
					totalRepositoryContributions: number;
				}
			>;
		}>(token, `query { user(login: "${login}") { ${aliases} } }`);
	});

	return results.flatMap((res, b) =>
		batches[b].map((_, i) => {
			const w = res.user[`w${i}`];
			return {
				commits: w?.totalCommitContributions ?? 0,
				restricted: w?.restrictedContributionsCount ?? 0,
				issues: w?.totalIssueContributions ?? 0,
				pullRequests: w?.totalPullRequestContributions ?? 0,
				reviews: w?.totalPullRequestReviewContributions ?? 0,
				repos: w?.totalRepositoryContributions ?? 0,
			};
		}),
	);
}

/** Accumulate per-month counts into separate cumulative series (public + private). */
export function buildPoints(
	windows: MonthWindow[],
	monthly: MonthlyCount[],
): CommitPoint[] {
	let cumulative = 0;
	let restrictedCumulative = 0;
	return windows.map((w, i) => {
		const m = monthly[i];
		const commits = m?.commits ?? 0;
		const restricted = m?.restricted ?? 0;
		cumulative += commits;
		restrictedCumulative += restricted;
		return {
			date: w.label,
			commits,
			cumulative,
			restricted,
			restrictedCumulative,
			issues: m?.issues ?? 0,
			pullRequests: m?.pullRequests ?? 0,
			reviews: m?.reviews ?? 0,
			repos: m?.repos ?? 0,
		};
	});
}

/** Fetch a user's full lifetime commit history (no cache). */
export async function fetchCommitHistory(
	rawLogin: string,
	token: string,
): Promise<CommitHistory> {
	if (!token)
		throw new GitHubError("No GitHub token configured on the server.", 401);
	const user = await fetchProfile(rawLogin, token);
	const windows = monthlyWindows(new Date(user.createdAt), new Date());
	const monthly = await fetchMonthlyCommits(user.login, token, windows);
	const points = buildPoints(windows, monthly);
	const last = points.at(-1);
	return {
		user,
		points,
		total: last?.cumulative ?? 0,
		totalRestricted: last?.restrictedCumulative ?? 0,
		...sumContributionTypes(points),
	};
}
