/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsoringRouteImport } from './routes/sponsoring'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as UserRouteImport } from './routes/$user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsSlugRouteImport } from './routes/organizations.$slug'
import { Route as MetricsExplainedRouteImport } from './routes/metrics.explained'
import { Route as MetricsSlugRouteImport } from './routes/metrics.$slug'
import { Route as EmbedUserRouteImport } from './routes/embed.$user'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as Char91Char93SponsoringRouteImport } from './routes/[-].sponsoring'
import { Route as Char91Char93SlugRouteImport } from './routes/[-].$slug'
import { Route as Char91Char93MetricsIndexRouteImport } from './routes/[-].metrics.index'
import { Route as OgKindLoginRouteImport } from './routes/og.$kind.$login'
import { Route as Char91Char93OrganizationsSlugRouteImport } from './routes/[-].organizations.$slug'
import { Route as Char91Char93MetricsSlugRouteImport } from './routes/[-].metrics.$slug'

const SponsoringRoute = SponsoringRouteImport.update({
  id: '/sponsoring',
  path: '/sponsoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsSlugRoute = OrganizationsSlugRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsExplainedRoute = MetricsExplainedRouteImport.update({
  id: '/metrics/explained',
  path: '/metrics/explained',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsSlugRoute = MetricsSlugRouteImport.update({
  id: '/metrics/$slug',
  path: '/metrics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedUserRoute = EmbedUserRouteImport.update({
  id: '/embed/$user',
  path: '/embed/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93SponsoringRoute = Char91Char93SponsoringRouteImport.update({
  id: '/-/sponsoring',
  path: '/-/sponsoring',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93SlugRoute = Char91Char93SlugRouteImport.update({
  id: '/-/$slug',
  path: '/-/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93MetricsIndexRoute =
  Char91Char93MetricsIndexRouteImport.update({
    id: '/-/metrics/',
    path: '/-/metrics/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgKindLoginRoute = OgKindLoginRouteImport.update({
  id: '/og/$kind/$login',
  path: '/og/$kind/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91Char93OrganizationsSlugRoute =
  Char91Char93OrganizationsSlugRouteImport.update({
    id: '/-/organizations/$slug',
    path: '/-/organizations/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91Char93MetricsSlugRoute = Char91Char93MetricsSlugRouteImport.update({
  id: '/-/metrics/$slug',
  path: '/-/metrics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsoring': typeof SponsoringRoute
  '/-/$slug': typeof Char91Char93SlugRoute
  '/-/sponsoring': typeof Char91Char93SponsoringRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/-/metrics/$slug': typeof Char91Char93MetricsSlugRoute
  '/-/organizations/$slug': typeof Char91Char93OrganizationsSlugRoute
  '/og/$kind/$login': typeof OgKindLoginRoute
  '/-/metrics/': typeof Char91Char93MetricsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsoring': typeof SponsoringRoute
  '/-/$slug': typeof Char91Char93SlugRoute
  '/-/sponsoring': typeof Char91Char93SponsoringRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/-/metrics/$slug': typeof Char91Char93MetricsSlugRoute
  '/-/organizations/$slug': typeof Char91Char93OrganizationsSlugRoute
  '/og/$kind/$login': typeof OgKindLoginRoute
  '/-/metrics': typeof Char91Char93MetricsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsoring': typeof SponsoringRoute
  '/-/$slug': typeof Char91Char93SlugRoute
  '/-/sponsoring': typeof Char91Char93SponsoringRoute
  '/company/$slug': typeof CompanySlugRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/organizations/$slug': typeof OrganizationsSlugRoute
  '/-/metrics/$slug': typeof Char91Char93MetricsSlugRoute
  '/-/organizations/$slug': typeof Char91Char93OrganizationsSlugRoute
  '/og/$kind/$login': typeof OgKindLoginRoute
  '/-/metrics/': typeof Char91Char93MetricsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$user'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsoring'
    | '/-/$slug'
    | '/-/sponsoring'
    | '/company/$slug'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/organizations/$slug'
    | '/-/metrics/$slug'
    | '/-/organizations/$slug'
    | '/og/$kind/$login'
    | '/-/metrics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$user'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsoring'
    | '/-/$slug'
    | '/-/sponsoring'
    | '/company/$slug'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/organizations/$slug'
    | '/-/metrics/$slug'
    | '/-/organizations/$slug'
    | '/og/$kind/$login'
    | '/-/metrics'
  id:
    | '__root__'
    | '/'
    | '/$user'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsoring'
    | '/-/$slug'
    | '/-/sponsoring'
    | '/company/$slug'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/organizations/$slug'
    | '/-/metrics/$slug'
    | '/-/organizations/$slug'
    | '/og/$kind/$login'
    | '/-/metrics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsoringRoute: typeof SponsoringRoute
  Char91Char93SlugRoute: typeof Char91Char93SlugRoute
  Char91Char93SponsoringRoute: typeof Char91Char93SponsoringRoute
  CompanySlugRoute: typeof CompanySlugRoute
  EmbedUserRoute: typeof EmbedUserRoute
  MetricsSlugRoute: typeof MetricsSlugRoute
  MetricsExplainedRoute: typeof MetricsExplainedRoute
  OrganizationsSlugRoute: typeof OrganizationsSlugRoute
  Char91Char93MetricsSlugRoute: typeof Char91Char93MetricsSlugRoute
  Char91Char93OrganizationsSlugRoute: typeof Char91Char93OrganizationsSlugRoute
  OgKindLoginRoute: typeof OgKindLoginRoute
  Char91Char93MetricsIndexRoute: typeof Char91Char93MetricsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsoring': {
      id: '/sponsoring'
      path: '/sponsoring'
      fullPath: '/sponsoring'
      preLoaderRoute: typeof SponsoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/explained': {
      id: '/metrics/explained'
      path: '/metrics/explained'
      fullPath: '/metrics/explained'
      preLoaderRoute: typeof MetricsExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$slug': {
      id: '/metrics/$slug'
      path: '/metrics/$slug'
      fullPath: '/metrics/$slug'
      preLoaderRoute: typeof MetricsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$user': {
      id: '/embed/$user'
      path: '/embed/$user'
      fullPath: '/embed/$user'
      preLoaderRoute: typeof EmbedUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/sponsoring': {
      id: '/-/sponsoring'
      path: '/-/sponsoring'
      fullPath: '/-/sponsoring'
      preLoaderRoute: typeof Char91Char93SponsoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/$slug': {
      id: '/-/$slug'
      path: '/-/$slug'
      fullPath: '/-/$slug'
      preLoaderRoute: typeof Char91Char93SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/metrics/': {
      id: '/-/metrics/'
      path: '/-/metrics'
      fullPath: '/-/metrics/'
      preLoaderRoute: typeof Char91Char93MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$kind/$login': {
      id: '/og/$kind/$login'
      path: '/og/$kind/$login'
      fullPath: '/og/$kind/$login'
      preLoaderRoute: typeof OgKindLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/organizations/$slug': {
      id: '/-/organizations/$slug'
      path: '/-/organizations/$slug'
      fullPath: '/-/organizations/$slug'
      preLoaderRoute: typeof Char91Char93OrganizationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/-/metrics/$slug': {
      id: '/-/metrics/$slug'
      path: '/-/metrics/$slug'
      fullPath: '/-/metrics/$slug'
      preLoaderRoute: typeof Char91Char93MetricsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsoringRoute: SponsoringRoute,
  Char91Char93SlugRoute: Char91Char93SlugRoute,
  Char91Char93SponsoringRoute: Char91Char93SponsoringRoute,
  CompanySlugRoute: CompanySlugRoute,
  EmbedUserRoute: EmbedUserRoute,
  MetricsSlugRoute: MetricsSlugRoute,
  MetricsExplainedRoute: MetricsExplainedRoute,
  OrganizationsSlugRoute: OrganizationsSlugRoute,
  Char91Char93MetricsSlugRoute: Char91Char93MetricsSlugRoute,
  Char91Char93OrganizationsSlugRoute: Char91Char93OrganizationsSlugRoute,
  OgKindLoginRoute: OgKindLoginRoute,
  Char91Char93MetricsIndexRoute: Char91Char93MetricsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
