/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/$user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgLoginRouteImport } from './routes/org.$login'
import { Route as MetricsExplainedRouteImport } from './routes/metrics.explained'
import { Route as MetricsSlugRouteImport } from './routes/metrics.$slug'
import { Route as EmbedUserRouteImport } from './routes/embed.$user'

const UserRoute = UserRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgLoginRoute = OrgLoginRouteImport.update({
  id: '/org/$login',
  path: '/org/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsExplainedRoute = MetricsExplainedRouteImport.update({
  id: '/metrics/explained',
  path: '/metrics/explained',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsSlugRoute = MetricsSlugRouteImport.update({
  id: '/metrics/$slug',
  path: '/metrics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedUserRoute = EmbedUserRouteImport.update({
  id: '/embed/$user',
  path: '/embed/$user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/org/$login': typeof OrgLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/org/$login': typeof OrgLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/embed/$user': typeof EmbedUserRoute
  '/metrics/$slug': typeof MetricsSlugRoute
  '/metrics/explained': typeof MetricsExplainedRoute
  '/org/$login': typeof OrgLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$user'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/org/$login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$user'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/org/$login'
  id:
    | '__root__'
    | '/'
    | '/$user'
    | '/embed/$user'
    | '/metrics/$slug'
    | '/metrics/explained'
    | '/org/$login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRoute
  EmbedUserRoute: typeof EmbedUserRoute
  MetricsSlugRoute: typeof MetricsSlugRoute
  MetricsExplainedRoute: typeof MetricsExplainedRoute
  OrgLoginRoute: typeof OrgLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$login': {
      id: '/org/$login'
      path: '/org/$login'
      fullPath: '/org/$login'
      preLoaderRoute: typeof OrgLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/explained': {
      id: '/metrics/explained'
      path: '/metrics/explained'
      fullPath: '/metrics/explained'
      preLoaderRoute: typeof MetricsExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$slug': {
      id: '/metrics/$slug'
      path: '/metrics/$slug'
      fullPath: '/metrics/$slug'
      preLoaderRoute: typeof MetricsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$user': {
      id: '/embed/$user'
      path: '/embed/$user'
      fullPath: '/embed/$user'
      preLoaderRoute: typeof EmbedUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRoute,
  EmbedUserRoute: EmbedUserRoute,
  MetricsSlugRoute: MetricsSlugRoute,
  MetricsExplainedRoute: MetricsExplainedRoute,
  OrgLoginRoute: OrgLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
